# Site settings
title: heqzha@blog
email: heqzha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hequn Zhang, Interest areas is Game Engine Development and Intelligent Algorithms Research, This blog is about what I learnt and how I thought. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: heqzha
github_username: heqzha

# Build settings
markdown: rdiscount
permalink: /blog/:year/:month/:day/:title